version: '3.5'

services:
  db:
    image: mariadb:10.3
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: tegarsd5
      MYSQL_DATABASE: dbss
      MYSQL_USER: tegar
      MYSQL_PASSWORD: tegarsd5

  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - "80:80"
    environment:
      DB_HOST: localhost
      DB_PASSWORD: tegarsd5
      DB_NAME: dbss
      DB_USER: tegar
      WORDPRESS_SITE_URL: http://localhost
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"

volumes:
  db-data:
  site-data:

networks:
  default:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet: 192.168.91.0/24
